### ISSUE TITLE
HEADPHONES + MIX port uses OMTP wiring standard

### ISSUE THREAD

**Issue by antoniohof** [dennisppaul/klangstrom-hardware#2]
Klangstrom uses OMTP standard on HEADPHONES+MIC port

<img width="443" alt="Screen Shot 2021-07-07 at 12 43 52" src="https://user-images.githubusercontent.com/8311230/124746474-30c40680-df21-11eb-86cf-a9276c3a84e0.png">

If you want to connect apple headphones, for example, they use CTIA standard so you would need an adapter.

**Comment by dennisppaul** [comment]
future versions of KLST_TINY will have a CTIA/AHJ audio+mic connection. until then, as stated above, for KLST_TINY(v0.1) a *OMTP to CTIA/AHJ* adapter is required to connect e.g Apple headsets

**Comment by dennisppaul** [comment]
moved to [FAQ](https://klangstrom-for-arduino.dennisppaul.de/faq/)
